#include-once

; Trading operations
Global Const $GC_I_HEADER_TRADE_INITIATE = 0x0049        	; Initiate a trade with another player.
Global Const $GC_I_HEADER_TRADE_OTHER_INITIATE = 0x0000		; Someone Initiate a trade with you.
Global Const $GC_I_HEADER_TRADE_CANCEL = 0x0001          	; Cancel the current trade.
Global Const $GC_I_HEADER_TRADE_ADD_ITEM = 0x0002        	; Add an item to the trade offer.
Global Const $GC_I_HEADER_TRADE_SUBMIT_OFFER = 0x0003    	; Submit the current trade offer.
;~ Global Const $GC_I_HEADER_MAX_ATTRIBUTES_CONST = 0x0004  ; Maximum attributes constant (not in use).
Global Const $GC_I_HEADER_TRADE_REMOVE_ITEM = 0x0005     	; Remove an item from the trade offer.
Global Const $GC_I_HEADER_TRADE_CHANGE_OFFER = 0x0006    	; Change the trade offer made.
Global Const $GC_I_HEADER_TRADE_ACCEPT = 0x0007          	; Accept the trade offer.
;~ Global Const $GC_I_HEADER_DISCONNECT = 0x0008            ; Handle a disconnect event.
;~ Global Const $GC_I_HEADER_PING_REPLY = 0x0009            ; Respond to a ping request.
;~ Global Const $GC_I_HEADER_HEARTBEAT = 0x000A             ; Send a heartbeat signal to maintain connection.
;~ Global Const $GC_I_HEADER_PING_REQUEST = 0x000B          ; Send a ping request to another entity.
Global Const $GC_I_HEADER_ATTRIBUTE_DECREASE = 0x000E    	; Decrease an attribute value.
Global Const $GC_I_HEADER_ATTRIBUTE_INCREASE = 0x000F    	; Increase an attribute value.
Global Const $GC_I_HEADER_ATTRIBUTE_LOAD = 0x0010        	; Load attribute data.
Global Const $GC_I_HEADER_SEND_CHAT = 0x0064        		; Send chat command.

; Quest and Hero operations
Global Const $GC_I_HEADER_QUEST_ABANDON = 0x0011         	; Abandon the selected quest.
Global Const $GC_I_HEADER_QUEST_REQUEST_INFOS = 0x0012   ; Request information for a quest.
Global Const $GC_I_HEADER_QUEST_SET_ACTIVE = 0x0014      	; Set a quest as active.
Global Const $GC_I_HEADER_HERO_BEHAVIOR = 0x0015         	; Define hero behavior settings.
Global Const $GC_I_HEADER_HERO_LOCK_TARGET = 0x0016      	; Lock onto a specific target.
Global Const $GC_I_HEADER_HERO_SKILL_TOGGLE = 0x0019     	; Toggle a hero's skill on/off.
Global Const $GC_I_HEADER_HERO_FLAG_SINGLE = 0x001A      	; Flag hero for single-target actions.
Global Const $GC_I_HEADER_HERO_FLAG_ALL = 0x001B         	; Flag hero for multi-target actions. Flag all heroes and Clears All Flags from heroes.
Global Const $GC_I_HEADER_HERO_USE_SKILL = 0x001C        	; Hero uses a specified skill.
Global Const $GC_I_HEADER_HERO_ADD = 0x001E              	; Add a hero to the party or team.
Global Const $GC_I_HEADER_HERO_KICK = 0x001F             	; Remove a hero from the party or team.

; Action operations
Global Const $GC_I_HEADER_ACTION_ATTACK = 0x0026         	; Initiate an attack.
;~ Global Const $GC_I_HEADER_ATTACK_AGENT = 0x0024 			; Initiates an attack on a selected agent
Global Const $GC_I_HEADER_ACTION_CANCEL = 0x0028         	; Cancel the current action.
Global Const $GC_I_HEADER_BOND_DROP = 0x0029             	; Drop or remove a bond.
Global Const $GC_I_HEADER_CALL_TARGET = 0x23 				; Calls the target without attacking (Ctrl+Shift+Space)
Global Const $GC_I_HEADER_MAP_DRAW = 0x002B              	; Draw or update the map (not in use).
Global Const $GC_I_HEADER_DROP_ITEM = 0x002C             	; Drop an item from the inventory.
Global Const $GC_I_HEADER_DROP_GOLD = 0x002F             	; Drop gold or currency.
Global Const $GC_I_HEADER_ITEM_EQUIP = 0x0030            	; Equip an item.
Global Const $GC_I_HEADER_ITEM_EQUIP_HERO = 0x0031       	; Equip an item on a hero.
Global Const $GC_I_HEADER_INTERACT_PLAYER = 0x0033       	; Interact with another player.
Global Const $GC_I_HEADER_FACTION_DEPOSIT = 0x0035       	; Deposit resources into a faction bank.
Global Const $GC_I_HEADER_INTERACT_LIVING = 0x0039       	; Interact with a living entity.
Global Const $GC_I_HEADER_DIALOG_SEND = 0x003B           	; Send dialog choices.
Global Const $GC_I_HEADER_SKILL_EQUIP = 0x003C           	; Equip Skill from NPC Dialog.
Global Const $GC_I_HEADER_PLAYER_MOVE_COORD = 0x003E     	; Move player to specific coordinates (not in use).
Global Const $GC_I_HEADER_ITEM_INTERACT = 0x003F         	; Interact with an item.
Global Const $GC_I_HEADER_PLAYER_ROTATE = 0x0040         	; Rotate the player (not in use).
Global Const $GC_I_HEADER_PROFESSION_CHANGE = 0x0041     	; Change player's profession.
;~ Global Const $GC_I_HEADER_SKILLS_OPEN = 0x0040           ; Open the skills interface (not in use).
;~ Global Const $GC_I_HEADER_PROFESSION_ULOCK = 0x0040      ; Unlock a profession (not in use).
Global Const $GC_I_HEADER_SKILL_USE = 0x0046             	; Use a specific skill (not in use).
Global Const $GC_I_HEADER_BUY_MATERIALS = 0x004A         	; Buy materials (not in use).
Global Const $GC_I_HEADER_REQUEST_QUOTE = 0x004C         	; Request a quote for services or goods (not in use).
Global Const $GC_I_HEADER_TRANSACT_ITEMS = 0x004D        	; Transaction of items (not in use).
Global Const $GC_I_HEADER_ITEM_UNEQUIP = 0x004F          	; Unequip an item.
Global Const $GC_I_HEADER_ITEM_UNEQUIP_HERO = 0x0050     	; Unequip an item from a hero.
Global Const $GC_I_HEADER_GADGET_INTERACT = 0x0051       	; Interact with a gadget.
Global Const $GC_I_HEADER_CHEST_OPEN = 0x0053            	; Open a treasure chest.
Global Const $GC_I_HEADER_TITLE_DISPLAY = 0x0058         	; Display a title above the character.
Global Const $GC_I_HEADER_TITLE_HIDE = 0x0059            	; Hide the displayed title.
Global Const $GC_I_HEADER_SKILLBAR_SKILL_SET = 0x005C    	; Set a skill on the skillbar.
Global Const $GC_I_HEADER_SKILLBAR_LOAD = 0x005D         	; Load the skillbar settings.
;~ Global Const $GC_I_HEADER_SKILLBAR_SKILL_REPLACE = 0x005C; Replace a skill on the skillbar (not in use).
Global Const $GC_I_HEADER_CINEMATIC_SKIP = 0x0063        	; Skip a cinematic scene.
Global Const $GC_I_HEADER_SEND_CHAT_MESSAGE = 0x0064     	; Send a message in the chat.
Global Const $GC_I_HEADER_ITEM_DESTROY = 0x0069          	; Destroy an item.
Global Const $GC_I_HEADER_ITEM_IDENTIFY = 0x006C         	; Identify the properties of an item.
Global Const $GC_I_HEADER_TOME_UNLOCK_SKILL = 0x006D     	; Unlock a skill using a tome.
Global Const $GC_I_HEADER_ITEM_MOVE = 0x0072             	; Move an item within the inventory.
Global Const $GC_I_HEADER_ITEMS_ACCEPT_UNCLAIMED = 0x0073	; Accept unclaimed items.
Global Const $GC_I_HEADER_ITEM_SPLIT_STACK = 0x0075      	; Split an item stack.
Global Const $GC_I_HEADER_ITEM_SALVAGE_SESSION_OPEN = 0x0077   ; Open a salvage session.
Global Const $GC_I_HEADER_ITEM_SALVAGE_SESSION_CANCEL = 0x0078 ; Cancel the salvage session.
Global Const $GC_I_HEADER_ITEM_SALVAGE_SESSION_DONE = 0x0079   ; Complete the salvage session.
Global Const $GC_I_HEADER_ITEM_SALVAGE_MATERIALS = 0x007A      ; Salvage materials from an item.
Global Const $GC_I_HEADER_ITEM_SALVAGE_UPGRADE = 0x007B        ; Upgrade an item through salvage.
Global Const $GC_I_HEADER_ITEM_CHANGE_GOLD = 0x007C            ; Change the gold amount for an item.
Global Const $GC_I_HEADER_ITEM_USE = 0x007E                    ; Use an item.
Global Const $GC_I_HEADER_UPGRADE_SESSION_ADD = 0x007F         ; Add a component to an upgrade session.
Global Const $GC_I_HEADER_UPGRADE_SESSION_OPEN = 0x0080        ; Open an item upgrade session.
Global Const $GC_I_HEADER_UPGRADE_SESSION_CANCEL = 0x0081      ; Cancel an item upgrade session.
Global Const $GC_I_HEADER_UPGRADE_SESSION_END = 0x0082         ; Confirm an item upgrade session.
Global Const $GC_I_HEADER_UPGRADE_SESSION_VALID_UPGRADE = $GC_I_HEADER_UPGRADE_SESSION_END ; Legacy name of the confirm header.
;~ Global Const $GC_I_HEADER_INSTANCE_LOAD_REQUEST_SPAWN = 0x0086 ; Request spawn in an instance (not in use).
;~ Global Const $GC_I_HEADER_INSTANCE_LOAD_REQUEST_PLAYERS = 0x008E; Request player data in an instance (not in use).
;~ Global Const $GC_I_HEADER_INSTANCE_LOAD_REQUEST_ITEMS = 0x008F ; Request item data in an instance (not in use).
Global Const $GC_I_HEADER_PARTY_SET_DIFFICULTY = 0x009B        ; Set the difficulty for a party quest or dungeon.
Global Const $GC_I_HEADER_PARTY_ACCEPT_INVITE = 0x009C         ; Accept an invitation to join a party.
;~ Global Const $GC_I_HEADER_PARTY_ACCEPT_CANCEL = 0x009B      ; Cancel party invitation acceptance (not in use).
Global Const $GC_I_HEADER_PARTY_ACCEPT_REFUSE = 0x009E         ; Refuse an invitation to join a party.
Global Const $GC_I_HEADER_PARTY_INVITE_NPC = 0x009F            ; Invite an NPC to the party.
Global Const $GC_I_HEADER_PARTY_INVITE_PLAYER = 0x00A0         ; Invite a player to the party.
Global Const $GC_I_HEADER_PARTY_LEAVE_GROUP = 0x00A2           ; Leave the current party or group.
Global Const $GC_I_HEADER_PARTY_CANCEL_ENTER_CHALLENGE = 0x00A3; Cancel entering a challenge or cancel map travel.
Global Const $GC_I_HEADER_PARTY_ENTER_CHALLENGE = 0x00A5       ; Enter a challenge or dungeon.
Global Const $GC_I_HEADER_PARTY_RETURN_TO_OUTPOST = 0x00A7     ; Return the party to the outpost.
Global Const $GC_I_HEADER_PARTY_KICK_NPC = 0x00A8              ; Kick an NPC from the party.
Global Const $GC_I_HEADER_PARTY_KICK_PLAYER = 0x00A9           ; Kick a player from the party.
;~ Global Const $GC_I_HEADER_PARTY_SEARCH_SEEK = 0x00A8        ; Search for a party (not in use).
;~ Global Const $GC_I_HEADER_PARTY_SEARCH_CANCEL = 0x00A9      ; Cancel party search (not in use).
;~ Global Const $GC_I_HEADER_PARTY_SEARCH_REQUEST_JOIN = 0x00AA   ; Request to join a party search (not in use).
;~ Global Const $GC_I_HEADER_PARTY_ENTER_FOREIGN_CHALLENGE = 0x00AD; Enter a foreign challenge (not in use).
;~ Global Const $GC_I_HEADER_PARTY_SEARCH_REQUEST_REPLY = 0x00AB  ; Reply to a party search request (not in use).
;~ Global Const $GC_I_HEADER_PARTY_SEARCH_TYPE = 0x00AC        ; Set the search type for party search (not in use).
Global Const $GC_I_HEADER_PARTY_ENTER_GUILD_HALL = 0x00B0      ; Enter a guild hall.
Global Const $GC_I_HEADER_PARTY_TRAVEL = 0x00B1                ; Travel to a new location with the party.
Global Const $GC_I_HEADER_PARTY_LEAVE_GUILD_HALL = 0x00B2      ; Leave the guild hall.
Global Const $GC_I_HEADER_PARTY_TICK = 0x00AF         		   ; Manage party ticks.
Global Const $GC_I_HEADER_EQUIP_BAG = 0x6B						; to equipe bag item
Global Const $GC_I_HEADER_SWITCH_SET = 0x32						; Switch weapon set
Global Const $GC_I_HEADER_TARGET_AGENT = 0xC1					; target an agent

Global Const $GC_I_HEADER_BUY_GUILD_CAPE = 0x0038 ; header used when buy a cape
Global Const $GC_I_HEADER_SHOW_HIDE = 0x0057 ; show or hide helmt/cape/Costum
Global Const $GC_I_HEADER_GUILD_ANNOUCEMENTS = 0x00BE ; Modifie guild annoucements
Global Const $GC_I_HEADER_GUILD_SET_OFFICER = 0x00BD ; Modifie guild member role
